# Generated by Django 4.0.4 on 2022-06-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSHA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(unique=True, verbose_name='User ID')),
                ('name', models.TextField(unique=True, verbose_name='Username')),
                ('user_sha', models.TextField(unique=True, verbose_name='User token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Auth time')),
            ],
        ),
    ]
