# Generated by Django 4.0.4 on 2022-06-08 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_usersha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersha',
            options={'verbose_name': 'User SHA', 'verbose_name_plural': 'Users SHA'},
        ),
    ]
